### PR TITLE
Renaming clust_var to clusters, etc

### PR DESCRIPTION
**Pull request by nfultz**

### CODE REVIEW

**Comment by nfultz** [comment]
Locally this passes R CMD check, if we get a clean build out of travis, we should upload to cran.

**Comment by graemeblair** [comment]
can we address https://github.com/DeclareDesign/randomizr/issues/26 before we push to CRAN, @nfultz ?

**Comment by nfultz** [comment]
I'll take a look this afternoon and open a new pr if needed.

**Comment by graemeblair** [comment]
Sounds good -- otherwise agree we're good to go on pushing to CRAN!

**Pull request merged**
